apiVersion: v1
items:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "kitchensink-pipeline"
  spec:
    source:
      type: "Git"
      git:
        uri: "http://gogs.cicd.svc:3000/gogs/kitchensink"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
kind: List
metadata: []
